### ISSUE TITLE
Use case?

### ISSUE THREAD

**Issue by vincentamari** [esimonetti/SampleSugarAccountsCustomVisibility#1]
Hi, I'm struggling to think of a use case where this is needed, instead of standard functionality by creating an Admin Team and assigning that team to the record requiring only admins to access it?

**Comment by esimonetti** [comment]
There are plenty of use cases that can involve custom visibility rules. This was just an example on how to implement it, in full, at the time.

With custom visibility you could make a record only visible to the assigned user and no-one else as an example (not even admins if you really wanted to), nor the user's reporting line.

There might be cases especially for highly regulated environments (eg: banking for customers with potential conflicts of interests), or even if a system is tracking HR matters, where you would want something of this sort in place.

But obviously it is a deep customisation and it has to be designed thoughtfully, to make sure performance across the system is not impacted. The SQL queries that are generated and executed by the visibility are completed everywhere in the system when interacting with records.

Hope this gives you a hint on where this could be useful.
